spring:
  cloud:
    gateway:
      mvc:
        routes:
          - id : r1
            uri : http://127.0.0.1:8081/
            predicates :
              - Path=/clients/**

          - id : r2
            uri : http://127.0.0.1:8082/
            predicates :
              - Path=/products/**

  application:
    name: gateway-service

server:
  port: 8888
eureka:
  client:
    fetch-registry: false
    register-with-eureka: false